stages:
  - build
  - deploy

build-front-end-job:
  stage: build
  image: node:latest
  script:
    - cd ghi
    - npm install
    - npm run build
  artifacts:
    paths:
      - ghi/build/

pages:
  stage: deploy
  rules:
    # Only run if pushing to the main branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - build-front-end-job
  needs:
    - build-front-end-job
  script:
    - mv ghi/build public
  artifacts:
    paths:
      - public
