stages:
  - build
  - deploy

  variables:
    CORS_HOST: https://b_matran.gitlab.io

build project:
  stage: build
  image: node:lts-bullseye
  script:
    - cd ghi/app/
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - ghi/app/build/

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # CHANGE BACK TO CI_DEFAULT_BRANCH WHEN DEPLOYING ON MAIN
  dependencies:
    - build project
  needs:
    - build project
  script:
    - mv ghi/app/build/ public
  artifacts:
    paths:
      - public
