stages:
  - build
  - deploy

build project:
  stage: build
  image: node:lts-bullseye
  script:
    - cd ghi/app/
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - ghi/build/

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # CHANGE BACK TO CI_DEFAULT_BRANCH WHEN DEPLOYING ON MAIN
  dependencies:
    - build-front-end-job
  needs:
    - build-front-end-job
  script:
    - mv ghi/build/ public
  artifacts:
    paths:
      - public
