stages:
  - build
  - deploy

build-front-end-job:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run build
  artifact:
    paths:
      - build/

netlify:
  stage: deploy
  image: node:latest
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir=build --prod
