stages:
  - build
  - deploy

build project:
  stage: build
  image: node:lts-bullseye
  script:
    - cd ghi/app/
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - ghi/build/

netlify:
  stage: deploy
  image: node:lts-bullseye
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir==build --prod
