stages:
  - build
  - deploy

build project:
  stage: build
  image: node:lts-bullseye
  script:
    - cd ghi
    - npm install
    - npm run build
  artifacts:
    paths:
      - ghi/app/build/

netlify:
  stage: deploy
  image: node:lts-bullseye
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir==build --prod
