stages:
  - build
  - deploy

build project:
  stage: build
  image: node: 15
  script:
    - npm install
    - npm build

netlify:
  stage: deploy
  image: node:15
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir==build --prod
