# Generated by Django 4.0.3 on 2022-12-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autovo',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
